### ISSUE TITLE
Can't access on private mode in Firefox

### ISSUE THREAD

**Issue by elvus** [Ajaxy/telegram-tt#10]
the web crashes
![Screenshot_2021-04-29 Telegram](https://user-images.githubusercontent.com/24416449/116557316-54892180-a8cc-11eb-9bc1-bc97eb76b699.png)

**Comment by Ajaxy** [comment]
@elvus Thanks for the report. Please provide more information:

- OS and browser version.
- Does the issue constantly reproduce for you?
- What happens if you try another browser?

**Comment by elvus** [comment]
Sorry only happens in private mode
* OS: Windows 10
* Browser: Firefox 88.0 (64-bit)
* In others browsers works (Chrome, Chromium)

**Comment by Ajaxy** [comment]
Fixed now.

@elvus Can you please confirm? Browser tab refresh is needed.

**Comment by elvus** [comment]
Fixed 💪
