### ISSUE TITLE
Chat not shown when browser resized

### ISSUE THREAD

**Issue by foremtehan** [Ajaxy/telegram-tt#100]
1. Open telegram in firefox 95.0.2 (64-bit) (windows 10)
2. then restore down (resize) the browser to mobile resolution
3. click on some of chats

it doesnt show the chat

**Comment by Ajaxy** [comment]
Can you post a screen video please?

**Comment by foremtehan** [comment]
@Ajaxy ok here you go:

https://user-images.githubusercontent.com/53290883/148538797-9f4304d0-b018-4b72-95ec-016f7c8468f4.mp4
