### ISSUE TITLE
Unable to resize Telegran WebZ dialog width.

### ISSUE THREAD

**Issue by TokugawaTFC** [Ajaxy/telegram-tt#105]

**Comment by TokugawaTFC** [comment]
Cannot resize the Telegram WebZ PWA. I have been unable to resize it to a smaller width. This used to work previously

The Telegram version I am currently using is 1.30.5. This is on a an HP Chromebook X 360 14 with Chrome 97.

Dragging any corner or side of the dialog does not make the width smaller.

**Comment by Ajaxy** [comment]
Does refreshing the page not help? Can you attach a screenshot?

**Comment by TokugawaTFC** [comment]
Refreshing the PWA does not help
![Screenshot 2022-01-24 9 40 35 AM](https://user-images.githubusercontent.com/11012495/150804912-32d96cc8-3485-4514-adc0-3d1b978f6d4b.png)
.

**Comment by Ajaxy** [comment]
Which device are you using it on? Does it have a mobile screen layout? I do not see the middle column on your screenshot.

**Comment by TokugawaTFC** [comment]
I'm using an HP Chromebook X 360 14 with Chrome 97 and Telegram in a PWA.

![Screenshot 2022-01-24 4 53 36 PM](https://user-images.githubusercontent.com/11012495/150871288-18edde23-a50c-47ca-add8-cb37ffd6a9f7.png)

**Comment by Ajaxy** [comment]
From your screenshot I can see that the app takes the entire width of your system window. So probably, that's a restriction of your system?

**Comment by TokugawaTFC** [comment]
I'm not sure what you mean by system window. This is on a laptop not a phone. Re-sizing used to work fine a few builds ago so something in the OS or the Telegram PWA changed. Just in case it was not clear this is a Chrome OS laptop.

**Comment by TokugawaTFC** [comment]
This might help. Here is a screenshot of the whole desktop.
![Screenshot 2022-01-24 5 33 28 PM](https://user-images.githubusercontent.com/11012495/150876276-7e9603af-45a0-4eb7-9a84-3ffd241806cb.png)

**Comment by Ajaxy** [comment]
PWA can not control the minimum size of the window itself. Web Z can only allow you to resize the column width when in multicolumn layout. To enter multicolumn layout you need to manually resize the window to make it wider or to use a fullscreen button (black square icon on the right top).

**Comment by TokugawaTFC** [comment]
I'm not sure how else to say this. It DID work before. I cannot resize the width at all right now (that's the problem). When I use the the fullscreen button it maximizes the dialog and I still cannot resize it. Is there some other setting I need to change for me to be able to resize it again?

**Comment by Ajaxy** [comment]
Can you please attach a screenshot of the maximized window?

**Comment by TokugawaTFC** [comment]
![Screenshot 2022-01-25 9 19 04 AM](https://user-images.githubusercontent.com/11012495/150993966-34b6e076-44f2-4dc6-9357-2933e0dbece9.png)

**Comment by Ajaxy** [comment]
So here is a green line. If you drag it — you will be able to resize the left column. That's the only thing a PWA can do.

![image](https://user-images.githubusercontent.com/357153/151040578-847e810f-a473-4b75-b0c6-321bfd306a70.png)

**Comment by TokugawaTFC** [comment]
Ok, Thanks. Not sure what changed but I was able to resize is previously all the way from the left pane.
