### ISSUE TITLE
Private calls

### ISSUE THREAD

**Issue by etumyan** [Ajaxy/telegram-tt#108]
Hey, first of all thank you for the great application!

Just wondering are there any plans to add private audio/video calls like in the native apps (without creating a group) or that is just not possible due to restrictions of Telegram API?

Thanks in advance.

**Comment by Ajaxy** [comment]
Hey, for that to happen, we need that all other Telegram apps are updated to a newer protocol (because the old protocol is not feasible for web). We expect that to happen in this year.
