### ISSUE TITLE
Let user disable background notifications

### ISSUE THREAD

**Issue by andryandrew** [Ajaxy/telegram-tt#11]
In the legacy webapp, there was a switch to disable background notifications (i.e. desktop notifications when telegram's tab is not open). In the new webapps, it does not appear to be implemented yet.

Is there a workaround by playing with Chrome/Firefox permissions?

**Comment by Ajaxy** [comment]
You can do it this way:

<img src="https://user-images.githubusercontent.com/357153/116681193-5084fe80-a9b5-11eb-8d3a-429673b3f549.png" width="400" />

**Comment by andryandrew** [comment]
That disables all notifications, even when the Telegram tab is open

**Comment by andryandrew** [comment]
For reference, this is how it looks in the legacy app:
![image](https://user-images.githubusercontent.com/29781022/116681801-bbcad280-a9ad-11eb-9060-1cdc5904653a.png)

**Comment by Ajaxy** [comment]
Added a while ago (Settings > Notifications).
