### ISSUE TITLE
Menu background is not blurred in Firefox

### ISSUE THREAD

**Issue by ingria** [Ajaxy/telegram-tt#113]
![Screenshot from 2022-02-26 15-50-58](https://user-images.githubusercontent.com/2178368/155843991-bd76cdeb-2a71-4cb1-b917-cb3a1de70756.png)

**Comment by Ajaxy** [comment]
The transparency issue is fixed in Web Z 1.35.2. Thanks for your feedback.

**Comment by mradermaxlol** [comment]
@Ajaxy should [disabling the transparency feature completely](https://github.com/Ajaxy/telegram-tt/commit/cd04a2c689ad77c45edc63c9e283524c11620f48) be considered as fixing the issue?

**Comment by Ajaxy** [comment]
Yes, as Firefox [does not support](https://stackoverflow.com/questions/38145368/css-workaround-to-backdrop-filter) `backdrop-filter`.

**Comment by mradermaxlol** [comment]
Sounds legit. It seems like Firefox could [gain](https://bugzilla.mozilla.org/show_bug.cgi?id=1578503) [support](https://bugzilla.mozilla.org/show_bug.cgi?id=1749625) for this feature in the foreseeable future, though.
