### ISSUE TITLE
Own text color contrast is too low for the dark theme

### ISSUE THREAD

**Issue by Vistinum** [Ajaxy/telegram-tt#116]
Text color: [#FFFFFF](https://github.com/Ajaxy/telegram-tt/blob/bc36690d0041859e00b081bb59de08eea4d237d9/src/styles/themes.json#L18)
Background color: [#8774E1](https://github.com/Ajaxy/telegram-tt/blob/bc36690d0041859e00b081bb59de08eea4d237d9/src/styles/themes.json#L11)
Contrast ratio: 3.73:1

[WCAG](https://www.w3.org/TR/WCAG21/#contrast-minimum), for example, defines the minimum contrast (AA) to be 4.5:1 and the enhanced contrast (AAA) to be 7:1.
[Apple](https://developer.apple.com/design/human-interface-guidelines/business-chat/visual-design/color/), for another example, uses the same minimum of 4.5:1 while recommending 7:1.

**Comment by Ajaxy** [comment]
Thanks for the report. Fixed in 73432c957b0d0f1ee0140cc1214fa7c28d6224fa and 0088f1bcfb4e35c9c5ab7723c0383e8e87119dff.
