### ISSUE TITLE
Rename Telegram Web Z

### ISSUE THREAD

**Issue by dmserebr** [Ajaxy/telegram-tt#123]
During the recent month, the currently used name may have some negative connotations for a large number of people, especially in Eastern Europe.

Is it possible to consider renaming this project alias (i.e., change Z to some other letter)? Actually I'm not sure how many changes this would require (especially from the Telegram team) and is it really feasible. However, I assume that a lot of people would expect this change.

**Comment by Ajaxy** [comment]
Although we are strongly against the current war, we are also against excessive cancel culture and non-rational symbolism.

**Comment by megapro17** [comment]
And you did it anyway
Great

**Comment by PurpleTape** [comment]
You forgot to put on your red "letter fight" nose 🤡
