### ISSUE TITLE
Not staying logged in on Firefox

### ISSUE THREAD

**Issue by cbix** [Ajaxy/telegram-tt#13]
I'm trying to use https://webz.telegram.org/ with Firefox 88.0 on Arch Linux, but whenever the page is refreshed (or restarting the browser), I get logged out and need to enter the login manually again. This issue doesn't occur on Chromium.

**Comment by elvus** [comment]
Firefox disables storages in private mode, that's why session "expires", application can't save it. If you even reload the page, result will be the same. You can get the same behavior just by turning off the "Keep me signed in" on login.

**Comment by cbix** [comment]
Thanks for the hint. This is not happening in private mode, also I turned off _Tracking Protection_ and uBlock for `webz.telegram.org`, but it didn't help.

Or is it using a different domain for session cookies/storage?

**Comment by Ajaxy** [comment]
> This is not happening in private mode

@cbix Do you mean that the browser _does_ save the session in private mode, but _does not_ in regular mode?

**Comment by cbix** [comment]
No, I mean that I'm not using private mode.

**Comment by Ajaxy** [comment]
Then the issue seems to be specific to Linux/Firefox. I will try to test it out there.

**Comment by Ajaxy** [comment]
@cbix Can you please make a screenshot of a console with these errors?

**Comment by cbix** [comment]
![Screenshot from 2021-05-05 18-23-43](https://user-images.githubusercontent.com/1295945/117175382-1198e380-adcf-11eb-9105-585507afe535.png)

**Comment by cbix** [comment]
Ok, this warning led me to clearing site storage in Firefox for some other domains (the old web.telegram.org still used up 2 GB of data) and after a browser restart this problem went away so now I'm staying logged in.

Weird though that I haven't noticed any problems with other sites using localstorage since ... Closing this for now, maybe telegram-tt could handle these Exceptions in a more user-friendly way, but it's an edge case nonetheless.

**Comment by Ajaxy** [comment]
> Ok, this warning led me to clearing site storage in Firefox for some other domains (the old web.telegram.org still used up 2 GB of data) and after a browser restart this problem went away so now I'm staying logged in.
> 
> Weird though that I haven't noticed any problems with other sites using localstorage since ... Closing this for now, maybe telegram-tt could handle these Exceptions in a more user-friendly way, but it's an edge case nonetheless.

This sounds great! Thanks a lot for the information. Yes, we will think about a more user-friendly way to handle that, definitely.
