### ISSUE TITLE
[feature request] video calls please

### ISSUE THREAD

**Issue by lattice0** [Ajaxy/telegram-tt#131]
would be nice, thanks!

**Comment by Ajaxy** [comment]
We do have video calls. What device and browser are you on?

**Comment by lattice0** [comment]
Ubuntu, firefox

-------- Mensagem Original --------
Ativo 17 de abr. de 2022 08:57, Alexander Zinchuk escreveu:

**Comment by Ajaxy** [comment]
Firefox is not supported, unfortunately, but we are working on it. So far, you can use Chrome, for example.

**Comment by lattice0** [comment]
any updates on this?
