### ISSUE TITLE
Context menu on photo messages

### ISSUE THREAD

**Issue by LeonTheOriginal** [Ajaxy/telegram-tt#132]
Using a touchscreen device and Telegram Web Z, there seems to be no option to access the context menu of a message with a photo without additional caption text. (Single click on the photo opens the photo viewer, long press selects the message, additional single click just deselects the message.)
For comparison, in the Web K version, the menu is accessible by clicking on the timestamp.
It would be nice if there was also an option (or if there is already one, an easier way) to open the context menu.

**Comment by Ajaxy** [comment]
You can just tap outside of a message.

**Comment by LeonTheOriginal** [comment]
Thanks for the reply. I actually never tried that.
