### ISSUE TITLE
Fullscreen components on tablet width

### ISSUE THREAD

**Issue by severoemanuel** [Ajaxy/telegram-tt#134]
Hello, I usually use telegram in my opera sidebar, and when the width reaches the size of a tablet more or less, the chat content starts to disappear from the screen as you can see in the video below.

https://user-images.githubusercontent.com/46508229/164070336-66480515-c657-4c3f-8583-291ce3572625.mp4

Can you just make the chat fullscreen instead of showing it on the side when its content starts to scroll off screen?

**Comment by Ajaxy** [comment]
We have different layouts which are supposed to look better on each device (desktop, tablet, mobile).
