### ISSUE TITLE
Some text isn't translated in WebZ but it has translations in Translations platform

### ISSUE THREAD

**Issue by Muaath5** [Ajaxy/telegram-tt#14]
Hi,
I converted the language to Arabic (`ar`), But there's some text still in English!!
Note that text has translations in [Translations platform](https://translations.telegram.org).

## Screenshots
<img src="https://user-images.githubusercontent.com/60256639/116874168-862e1f80-ac21-11eb-9610-cfd1bb16db9f.png" alt="Screenshot for the problem" width="150">

## Steps to reproduce
1. Open [Telegram WebZ](https://webz.telegram.org)
2. Sign in
3. Change the language to Arabic (`ar`)
4. Open the menu
5. You'll find `Dark Mode`, `Telegram features` untranslated!!
6. Open settings
7. You'll find `General Settings`, `Edit Profile` untranslated!!

**Comment by Ajaxy** [comment]
@Muaath5, Can you please provide direct links to the correct translations? That would help a lot.

**Comment by Muaath5** [comment]
> @Muaath5, Can you please provide direct links to the correct translations? That would help a lot.

Ok, These is links in translations platform.

[Dark mode (Main menu)](https://translations.telegram.org/ar/tdesktop/general/lng_menu_night_mode)
[Edit profile (Settings)](https://translations.telegram.org/ar/tdesktop/settings/lng_settings_information)
[Telegram features (Main menu)](https://translations.telegram.org/ar/android/general/TelegramFeatures)
[All chats (Folder)](https://translations.telegram.org/ar/tdesktop/general/lng_filters_all)
[Explain Bio (Edit profile page, Under the bio)](https://translations.telegram.org/ar/tdesktop/settings/lng_settings_about_bio)
[This link opens chat with you (Edit profile page)](https://translations.telegram.org/ar/tdesktop/general/lng_username_link)
[Send with Ctrl+Enter (General settings)](https://translations.telegram.org/ar/tdesktop/settings/lng_settings_send_ctrlenter)
[Open menu (a small menu when mouse stay up in menu button)](https://translations.telegram.org/ar/android/unsorted/AccDescrOpenMenu2)

These are all texts I found untranslated.
Maybe I'll find more after more using.

**Comment by Muaath5** [comment]
@Ajaxy 
I also found these strings has translations but not translated:

* [Copy message link (In message context menu in groups or channels)](https://translations.telegram.org/ar/tdesktop/groups_and_channels/lng_context_copy_message_link).
* ["This will delete it for everyone in this chat." (After "delete message" menu clicked)](https://translations.telegram.org/ar/tdesktop/private_chats/lng_delete_for_everyone_hint)
* [Delete button (After "delete message" menu clicked)]

<img src="https://user-images.githubusercontent.com/60256639/117092998-60f7f900-ad68-11eb-88de-898313435b1a.png" alt="Window after delete message menu clicked">

**Comment by AbdullahMRiad** [comment]
Also when you copy a message (or its link I can't remember) isn't translated

**Comment by Ajaxy** [comment]
@Muaath5 Thanks for your contribution, we will be updating these translations.

**Comment by Ajaxy** [comment]
@Muaath5 Thanks for your contribution. Kindly check the updated version and feel free to report more missing translations.

**Comment by Muaath5** [comment]
Thank you, **Some** of missed translations was transnlated.

But see these photos:
![٢٠٢١٠٥٢١_١٥٣١٠٠](https://user-images.githubusercontent.com/60256639/119137782-dd1d5c80-ba49-11eb-9c9c-46e8d682c945.jpg)

Another photo:
![Screenshot_٢٠٢١٠٥٢١-١٥٢٩٤٢_Firefox](https://user-images.githubusercontent.com/60256639/119137815-e60e2e00-ba49-11eb-9b93-9c85f2e5c1b7.jpg)

**Comment by Ajaxy** [comment]
@Muaath5 Ah, can you refresh and check again now?

**Comment by Muaath5** [comment]
@Ajaxy Thank you for working!

**Comment by Muaath5** [comment]
Sorry for alot of untranslated text, But this is untranslated:
<img src="https://user-images.githubusercontent.com/60256639/119146356-376eeb00-ba53-11eb-8da4-8c4f373ae38f.png" width="500px">

**Comment by AbdullahMRiad** [comment]
They have to add WebK and WebZ to the translations platform

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Muaath5** [comment]
@Ajaxy Also I found some untranslated text to Arabic in: `Menu => Settings => Folders => Suggested folders`.

<img src="https://user-images.githubusercontent.com/60256639/119680680-14c14580-be4a-11eb-9a5b-4edfcffab687.png" alt="Untranslated text in Suggested folders sections" width="300px">

**Comment by Muaath5** [comment]
@Ajaxy I found also some untranslated strings, See here:
<img width="300px" alt="Untranslated text when sending (Poll)" src="https://user-images.githubusercontent.com/60256639/122708847-c72bd300-d265-11eb-97cc-9c3c3433577a.png">

And please add a placeholder to the text box

### Translations:
- Solution (`lng_polls_solution_title`)
- Option (`PollOptions`)
