### ISSUE TITLE
bug: voice message download does not work in Firefox

### ISSUE THREAD

**Issue by ilyapashuk** [Ajaxy/telegram-tt#153]
hello

my system:
win10 ltsc, Firefox 101.

when I try to download any voice message, the new tab opens and I sea only the blank screen.
download does not start, this new tab do not close until I close it manually.

and I can sea the following in the browser console:

GET
https://web.telegram.org/z/progressive/msg966897264-231:5463221146658805668?download
[HTTP/2 404 Not Found 85ms]

**Comment by MurzNN** [comment]
I've got the same problem with Chromium browser too!

**Comment by Ajaxy** [comment]
Fixed.
