### ISSUE TITLE
Open images and videos in fullscreen

### ISSUE THREAD

**Issue by wojpawlik** [Ajaxy/telegram-tt#161]

**Comment by Ajaxy** [comment]
This is already possible.

**Comment by wojpawlik** [comment]
I mean, photos and videos should default to fullscreen in narrow windows

**Comment by wojpawlik** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by Ajaxy** [comment]
Can you attach a screenshot of the way you see it on your device?

**Comment by wojpawlik** [comment]
![image](https://user-images.githubusercontent.com/23058303/190205169-12b1021d-12a2-4b44-aea4-168f676693be.png)

**Comment by Ajaxy** [comment]
So it looks like it is an expected behavior for the web app. Also, for video there is a fullscreen button on the bottom right.

**Comment by wojpawlik** [comment]
Could you at least add a fullscreen button to image viewer too?

**Comment by Ajaxy** [comment]
I think you can use standard Chrome hotkey for that.

**Comment by wojpawlik** [comment]
It doesn't resize the image. And <kbd>Esc</kbd> doesn't exit fullscreen. I'd be content if these were addressed.

![image](https://user-images.githubusercontent.com/23058303/191763875-79da2829-5167-4ea3-880d-100723dacba4.png)
