### ISSUE TITLE
GET /z/progressive/msg [404 Not Found]

### ISSUE THREAD

**Issue by ChenMoGe2** [Ajaxy/telegram-tt#169]
commit id:f2a686f873fb5a7199ae565c6abbd9c8d91e7b4a
os:centos7
env:npm run dev

When I receive video message in any chat,the video can not download and it's always loading on screen.I open console and it print https://10.8.0.1:11236/progressive/msg1560100594-3240:6154291039671682263 404 Not found.It not happen on [https://web.telegram.org/z/](url).So what's wrong with my deploy of server.

I just modify two files
.env file
```
NODE_ENV=development

TELEGRAM_T_API_ID=xxxxxx
TELEGRAM_T_API_HASH=xxxxxxxxxxxxxxxx
```
webpack.config.js
```
port: 1235,
```
and the nginx proxy port 11236->1235.I use openvpn to browse it.

**Comment by Ajaxy** [comment]
Fixed.
