### ISSUE TITLE
App refreshes on launching keyboard

### ISSUE THREAD

**Issue by sahilnarain** [Ajaxy/telegram-tt#17]
Device: Mi A2
Aspect Ratio: 18:9
Android: 10
Chrome: v90.0.4430.91
Keyboard: Gboard 

App reloads when screen dimensions change due to soft keyboard launch, making the app unusable.

Might have been triggered by changes in baffa925d88f5639c7125ada338063d90f52ad04 @Ajaxy 

For example, on the login screen, on tapping the phone number text box, the soft keyboard launches. As soon as the keyboard launches, src/util/windowSize.ts::handleResize() refreshes the window and takes the focus off the text box. On tapping the phone number text box, the problem repeats.

**Comment by sahilnarain** [comment]
Temporarily fixed due to commit revert in a684b4f1aa39d03288547f9b90f1f8c953e9c17e

**Comment by Ajaxy** [comment]
@sahilnarain Thanks a lot for the report. A fixed commit will be pushed soon.

**Comment by Ajaxy** [comment]
@sahilnarain Can you kindly confirm this is fixed now?

**Comment by sahilnarain** [comment]
@Ajaxy Yes, this works fine now.
