### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by therhenals** [Ajaxy/telegram-tt#18]
Notifications do not work, I use edge chromium

**Comment by Ajaxy** [comment]
@therhenals Can you kindly confirm this is fixed now?

**Comment by rogama25** [comment]
This is happening to me. Edge Linux Version 91.0.864.33 (Official build) beta (64-bit). I tried this version for the first time today, so there is not an older version cached or something.

Webz didn't ask for permission to send web notifications so it can't send them. My browser is set to ask when websites ask for permission to send notifications. After enabling manually notifications from the browser settings, it works. They still have no sound, not sure if it's intended or not.
