### ISSUE TITLE
Web version of Telegram sends viewport_changed event even if it was not changed.

### ISSUE THREAD

**Issue by heyqbnk** [Ajaxy/telegram-tt#189]
Hey, I am currently developing libraries ecosystem for Web Apps and noticed the bug, described here:
https://github.com/Telegram-Web-Apps/client-sdk/issues/13

You will probably find more bugs, connected with Web Apps by this filter:
https://github.com/Telegram-Web-Apps/client-sdk/labels/web

**Comment by Ajaxy** [comment]
@heyqbnk Hey, thanks for the report. All 4 issues are now fixed.
