### ISSUE TITLE
npm install - error

### ISSUE THREAD

**Issue by mariusiscoding** [Ajaxy/telegram-tt#194]
Hey can anyone help me?

I did all steps mentioned in the repo.

Node-Version: 18.12.1 (already tested multiple)
npm-Verison: 8.6.0

I get the following error:

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/marius/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! npm ERR! Failed to execute '/usr/local/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! npm ERR! node-pre-gyp info using node@18.12.1 | darwin | arm64
npm ERR! npm ERR! node-pre-gyp info check checked for "/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-darwin-unknown-arm64.tar.gz
npm ERR! npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-darwin-unknown-arm64.tar.gz 
npm ERR! npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@18.12.1 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-darwin-unknown-arm64.tar.gz 
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@9.0.0
npm ERR! npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! npm ERR! gyp info ok 
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@9.0.0
npm ERR! npm ERR! gyp info using node@18.12.1 | darwin | arm64
npm ERR! npm ERR! gyp info find Python using Python version 3.9.7 found at "/Users/marius/opt/anaconda3/bin/python"
npm ERR! npm ERR! gyp info spawn /Users/marius/opt/anaconda3/bin/python
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'make',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   '/Users/marius/Library/Caches/node-gyp/18.12.1/include/node/common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/marius/Library/Caches/node-gyp/18.12.1',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/marius/Library/Caches/node-gyp/18.12.1/<(target_arch)/node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! /bin/sh: pkg-config: command not found
npm ERR! npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! npm ERR! gyp ERR! configure error 
npm ERR! npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! npm ERR! gyp ERR! command "/usr/local/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! npm ERR! gyp ERR! cwd /Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas
npm ERR! npm ERR! gyp ERR! node -v v18.12.1
npm ERR! npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! npm ERR! gyp ERR! not ok 
npm ERR! npm ERR! node-pre-gyp ERR! build error 
npm ERR! npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! npm ERR! node-pre-gyp ERR! cwd /Users/marius/.npm/_cacache/tmp/git-clonefwi57F/node_modules/canvas
npm ERR! npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! npm ERR! node-pre-gyp ERR! not ok
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/marius/.npm/_logs/2022-11-15T10_33_21_375Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marius/.npm/_logs/2022-11-15T10_32_07_263Z-debug-0.log

**Comment by heyqbnk** [comment]
Problem is probably connected with `canvas` package. I already had the same issue in other projects. Try deleting `node_modules` directory and and use `npm install` again. Or use the other version of Node and do the same.

There is also strange log line as:
```
npm ERR! npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-darwin-unknown-arm64.tar.gz
```

Assuming, existence of substring `darwin-unknown-arm64`, there is some problem determining your OS or something like that.

**Comment by mariusiscoding** [comment]
Ok the install with errors above ar with my Mac Pro with M1 chip.

Tested again with Windows:
node: 'v18.12.1'
npm: '8.5.2' 

Again lots of errors:

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'telegram-t@1.55.0',
npm WARN EBADENGINE   required: { node: '^16.13', npm: '^8.5.2' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN skipping integrity check for git dependency ssh://git@github.com/korenskoy/emoji-data-ios.git 
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
Batchvorgang abbrechen (J/N)? j 
PS C:\Users\Kunde\Downloads\telegram-tt-master> npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'telegram-t@1.55.0',
npm WARN EBADENGINE   required: { node: '^16.13', npm: '^8.5.2' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.5.2' } 
npm WARN EBADENGINE }
npm WARN skipping integrity check for git dependency ssh://git@github.com/korenskoy/emoji-data-ios.git 
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\Kunde\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\Kunde\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! npm ERR! Warning: Missing input files:
npm ERR! npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! npm ERR! C:\GTK\bin\libpng14-14.dll
npm ERR! npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! npm ERR! Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "-m" hinzuf�gen.
npm ERR! npm ERR!   Backend.cc
npm ERR! npm ERR! C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\src\backend\Backend.h(3,10): fatal error C1083: Datei (Include) kann nicht ge�ffnet werden: "cairo.h": No such file or directory [C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\canvas.vcxproj]
npm ERR! npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Kunde\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! npm ERR! node-pre-gyp info using node@18.12.1 | win32 | x64
npm ERR! npm ERR! node-pre-gyp info check checked for "C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.0 and node@18.12.1 (node-v108 ABI, unknown) (falling 
back to source compile with node-gyp)
npm ERR! npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.0/canvas-v2.9.0-node-v108-win32-unknown-x64.tar.gz
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@8.4.1
npm ERR! npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! npm ERR! gyp info ok
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@8.4.1
npm ERR! npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! npm ERR! gyp info find Python using Python version 3.9.7 found at "C:\Users\Kunde\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! npm ERR! gyp info find VS using VS2019 (16.11.32630.194) found at:
npm ERR! npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! npm ERR! gyp info spawn C:\Users\Kunde\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\Kunde\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'msvs',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\canvas\\build\\config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\Kunde\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',  
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\Kunde\\AppData\\Local\\node-gyp\\Cache\\18.12.1\\include\\node\\common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Kunde\\AppData\\Local\\node-gyp\\Cache\\18.12.1',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Kunde\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Kunde\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.12.1\\\\<(target_arch)\\\\node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\canvas',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\canvas\\build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp info ok
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@8.4.1
npm ERR! npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! npm ERR! gyp info spawn args   '/nologo',
npm ERR! npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp ERR! build error
npm ERR! npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\Kunde\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kunde\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! npm ERR! gyp ERR! cwd C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas
npm ERR! npm ERR! gyp ERR! node -v v18.12.1
npm ERR! npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! npm ERR! node-pre-gyp ERR! build error
npm ERR! npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Kunde\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kunde\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone1oezEs\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! npm ERR! node-pre-gyp ERR! cwd C:\Users\Kunde\AppData\Local\npm-cache\_cacache\tmp\git-clone1oezEs\node_modules\canvas
npm ERR! npm ERR! node-pre-gyp ERR! node -v v18.12.1
npm ERR! npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! npm ERR! node-pre-gyp ERR! not ok
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Kunde\AppData\Local\npm-cache\_logs\2022-11-17T09_13_16_402Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kunde\AppData\Local\npm-cache\_logs\2022-11-17T09_13_07_767Z-debug-0.log

**Comment by mariusiscoding** [comment]
Ok fixed with using node version with exactly matching 16.13.
