### ISSUE TITLE
Corrupted audio covers

### ISSUE THREAD

**Issue by lmcsu** [Ajaxy/telegram-tt#209]
There's something wrong with audio covers, some of them become corrupted like this:

![image](https://user-images.githubusercontent.com/34189985/211481264-d33e0be4-b15f-4c7c-b5c9-1b4ba14f2d31.png)

Telegram desktop as it should be:
![image](https://user-images.githubusercontent.com/34189985/211481906-ae4845b2-20cc-44e9-a96c-f20d11a85eca.png)

Example file:
[02. Giddy Giddy Carousel.zip](https://github.com/Ajaxy/telegram-tt/files/10379712/02.Giddy.Giddy.Carousel.zip)

**Comment by zubiden** [comment]
That image is embedded in mp3 metadata. TDesktop tries to fetch a preview from iTunes beforehand while WebZ extracts file metadata.

File preview in Windows does the same extraction
![image](https://user-images.githubusercontent.com/19638254/213322763-49b0c199-ddab-4c45-9f9e-56f36a2500f1.png)

**Comment by lmcsu** [comment]
@zubiden I bet TDesktop tries to fetch a preview only in case if it cannot find it in the metadata.

I was me who put that cover inside the file.
Here I extracted it back:
[cover_90.zip](https://github.com/Ajaxy/telegram-tt/files/10475440/cover_90.zip)

And it works great everywhere except Telegram Web and (suddenly) Windows file preview.

**Comment by zubiden** [comment]
WebZ relies on _music-metadata-browser_ to extract cover pictures. Other websites with this library return similar results (https://audio-tag-analyzer.netlify.app/ as an example). Since Windows has the same issue, it's probably some edge case in metadata parsing or a slightly corrupted file that some libraries manage to restore.

**Comment by lmcsu** [comment]
Ok then there's something wrong with https://github.com/Borewit/music-metadata and/or ID3 itself, I just tried it directly.
And different ID3 versions give different result.
But anyway it's not related to WebZ, thank you everyone.
