### ISSUE TITLE
Can't install with npm i

### ISSUE THREAD

**Issue by iib0011** [Ajaxy/telegram-tt#211]
I'm using node v18.3.0 and npm 9.3.0. In package.json we have 
```javascript
"engines": {
    "node": "^18",
    "npm": "^9"
  }
```
I got this error.
npm ERR! code 1
npm ERR! git dep preparation failed

Which versions to use?

**Comment by Ajaxy** [comment]
Similar Node versions work in our case (macOS and Windows). However, you can also try v16.

**Comment by iib0011** [comment]
Still cant'. Had to use a Github Codespace
