### ISSUE TITLE
Reactor List does not display users' reactions

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#215]
- Reactions made by users are not displayed in the Reactor List.
- Hover style on an item intersects with the scrollbar (a small margin is needed).

<img src="https://user-images.githubusercontent.com/357153/213340803-0489e3e9-4169-48cc-bb24-6b42fb8bcea3.png" width="400" />

**Comment by iib0011** [comment]
The ReactorListModal props are 
```javascript
{
  isOpen,
  reactors,
  reactions,
  chatId,
  messageId,
  seenByUserIds,
  animationLevel,
  availableReactions,
}
```
but only the isOpen props is used in the code
