### ISSUE TITLE
Sometimes forwarding multiple messages breaks original order

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#216]
After refreshing the page the problem goes away.

**Comment by iib0011** [comment]
Can't reproduce

**Comment by Ajaxy** [comment]
Please, try selecting and forwarding 8-10 messages with media. The issue does not reproduce every time.

**Comment by Ajaxy** [comment]
So you have to open a chat, make sure the ID appears in the location hash, refresh the page and then exit the chat with \<Esc> – the location hash will no go away.

**Comment by Ajaxy** [comment]
Not reproducing.
