### ISSUE TITLE
Chat ID remains in the address bar after closing current chat with <Esc>

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#217]

**Comment by Ajaxy** [comment]
So you have to open a chat, make sure the ID appears in the location hash, refresh the page and then exit the chat with \<Esc> – the location hash will no go away.

**Comment by iib0011** [comment]
@Ajaxy In which function is the location hash change done?
Also, I looked at all the `addActionHandler('openChat')`. And one of them doesn't run when we call `openChat` from `getActions()`. Can you explain a little bit

**Comment by Ajaxy** [comment]
> In which function is the location hash change done?

`src/routing.ts`

> And one of them doesn't run when we call openChat from getActions(). Can you explain a little bit?

That is weird. Which one?

**Comment by iib0011** [comment]
None of the functions in this file is invoked after pressing Esc. Even in the case where it works

**Comment by Ajaxy** [comment]
We managed to fix that on our side.
