### ISSUE TITLE
Incorrect role flickers during the loading of channel subscribers list

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#219]
These users are not all admins. After a second, redundant statuses go away.

![image](https://user-images.githubusercontent.com/357153/213342105-a5d191ce-9a18-4f79-b88e-92e406aca20e.png)

**Comment by iib0011** [comment]
Can't reproduce. And what do you mean by statuses?

**Comment by Ajaxy** [comment]
By statuses, I meant "admin" marks.
