### ISSUE TITLE
Opening website from notification asks to login every time

### ISSUE THREAD

**Issue by vadimceb** [Ajaxy/telegram-tt#22]
Hello there,

Thank you for this cool web version!
Notification works fine but when clicking on them it ask to do a login every time.

#### Versions

OS: Ubuntu 20.04
Browser: Firefox 88.0.1

I'll try do some tests on other browsers

##### Update

on Chrome Version 90.0.4430.212 works fine

**Comment by Ajaxy** [comment]
Hi @vadimceb. Can you check if [this solution](https://github.com/Ajaxy/telegram-tt/issues/13#issuecomment-832835596) works for you?

**Comment by vadimceb** [comment]
The solution does not work. Cleared everything from browser but still when opening site by clicking the notifcation it asks to do a login. In the  browser console there are no warnings or errors. 

Works fine with chrome notifications

**Comment by Ajaxy** [comment]
@vadimceb Is it exactly related to the Push notifications? What if you simply refresh the browser tab?

**Comment by vadimceb** [comment]
@Ajaxy yes, it is directly related to push notifications.
Refreshing the page or even restarting the browser keeps me logged in.

**Comment by Ajaxy** [comment]
Fixed a while ago.
