### ISSUE TITLE
[Web Apps] `web_app_setup_main_button` does not update colors

### ISSUE THREAD

**Issue by heyqbnk** [Ajaxy/telegram-tt#229]
Call of `web_app_setup_main_button` does not update Main Button background and text colors.

### Steps to reproduce

1. Open [Web Apps polygon bot](https://t.me/webapps_polygon_bot) ([source code](https://github.com/Telegram-Web-Apps/bridge-polygon))
2. Open developers tools (F12)
3. Call Web Apps method:
```typescript
bridge.postEvent('web_app_setup_main_button', {
  text: 'Apply',
  text_color: '#00ff00',
  is_progress_visible: true,
  color: '#ff0000',
  is_visible: true,
  is_active: true
});
```
4. See colors not specified during method calling

### Expected behaviour

Telegram application applies colors specified in method.

**Comment by Ajaxy** [comment]
Done.
