### ISSUE TITLE
RTL the input when the user is writing Persian

### ISSUE THREAD

**Issue by mohammadizanloo55** [Ajaxy/telegram-tt#25]
like this picture (version k) : 
![telegram](https://user-images.githubusercontent.com/54350937/119248068-d6a2f800-bba3-11eb-82c3-a315b0a4295e.png)
but in your version : 
![telegram](https://user-images.githubusercontent.com/54350937/119248250-2635f380-bba5-11eb-8f2c-91c1c7806927.png)

**Comment by Ajaxy** [comment]
Thanks for the report, this is fixed.
