### ISSUE TITLE
FR: Allow logging in with SMS

### ISSUE THREAD

**Issue by anijatsu** [Ajaxy/telegram-tt#252]
I was surprised to see today that there was no alternative means of authentication other than to provide the code sent to another device. 
This is on Safari, iOS, iPhone XS. 
![IMG_9459](https://user-images.githubusercontent.com/1882015/235683526-bba72801-fc6a-4ff8-a72b-713bfa446deb.jpg)
Compared to the current App Store version of the mobile app:
![IMG_9461](https://user-images.githubusercontent.com/1882015/235683647-0a802d4d-24bd-46d2-8c1e-78131e2e7aa8.jpg)

**Comment by zubiden** [comment]
You're required to use an official mobile app for the first login
https://t.me/tginfoen/1611
https://t.me/tginfoen/1169

**Comment by anijatsu** [comment]
Closing since this is a platform related dependency, as explained above.
