### ISSUE TITLE
[PERF] Loading images use immense GPU

### ISSUE THREAD

**Issue by 4310V343k** [Ajaxy/telegram-tt#254]
Any time i see a loading (blurred with a progress spinner) image or video my GPU usage rises from 0% to 50% on a 3070.

<details>
<summary>Details</summary>

<table>
<tr>
 <td>Github
 <td>

![image](https://user-images.githubusercontent.com/56449763/236677566-b6d782eb-a71c-4353-9114-b04752385a56.png)

<tr>
 <td>Telegram with no loading images
 <td>

![image](https://user-images.githubusercontent.com/56449763/236677599-9f4109aa-b42b-4221-b9bd-c85fdc5a0ccd.png)

<tr>
 <td>Telegram with a loading image
 <td>

![image](https://user-images.githubusercontent.com/56449763/236677734-c559b883-b47b-440b-b31d-f9e007349569.png)

</table>

</details>

I don't know much about web, so if you can't reproduce the issue or want me to get some logs/performance metrics/tests let me know

**Comment by baseplate-admin** [comment]
What is your firefox version? 

This problem doesn't exist with my 1050 ti with latest nightly ( 123 )

**Comment by 4310V343k** [comment]
This issue is 7 months old and I'm pretty sure it was an edge case that I won't be able to reproduce on my new PC even if I wanted to
