### ISSUE TITLE
Downloading large attachments does not work

### ISSUE THREAD

**Issue by premek** [Ajaxy/telegram-tt#26]
Downloading ~70 MB attachment does not seem to work for me. it gets stuck halfway

**Comment by Ajaxy** [comment]
Hey there, thanks for the report. Please, provide your OS and browser version. What is the file you are trying to download? Did you try a couple of times with the same result? Thanks!

**Comment by premek** [comment]
chrome, Linux, it's a log file (large text file, maybe with some binary data in it, does it matter?) I tried a couple times with the same file, not with a different file

**Comment by Ajaxy** [comment]
> does it matter

Looks like it matters, since you say

> with the same file, not with a different file

Can you kindly share this file with us so we can debug it?

**Comment by premek** [comment]
[unzipme.zip](https://github.com/Ajaxy/telegram-tt/files/6546567/unzipme.zip)

I can reproduce with the `.log` file inside this zip (not the zip itself)

- send to yourself
- refresh page
- try to download

Funny thing is it seems to be able to crash the whole chrome if you leave it for a while

**Comment by Ajaxy** [comment]
Closing as outdated. Feel free to reopen if it's still relevant.
