### ISSUE TITLE
On Firefox Nightly sometimes https://webz.telegram.org/ goes into "Waiting for network..." state and never recovers

### ISSUE THREAD

**Issue by alex-mayorga** [Ajaxy/telegram-tt#27]
Platform:

Firefox Nightly on Windows 10 Pro Insider Dev Channel Build 21387 

Steps:

-     Log into https://webz.telegram.org/
-     Use Telegram as per normal

Result:
After some time https://webz.telegram.org/ goes into a "Waiting for network..." state and never recovers

Expected result:
https://webz.telegram.org/ works normally

No other program nor tabs show signs of any networking issue.

Profile:
https://share.firefox.dev/3y7k8p8

Filing here as requested on https://bugzilla.mozilla.org/show_bug.cgi?id=1711335#c2

**Comment by alex-mayorga** [comment]
¡Hola y'all!

Hope these lines find you well.

I haven't encountered this bug again since so resolving this report as WORKSFORME.

¡Gracias!
Alex

**Comment by Ajaxy** [comment]
Great to hear, thank you!
