### ISSUE TITLE
How to contribute code to telegram web client?

### ISSUE THREAD

**Issue by mohammadamin16** [Ajaxy/telegram-tt#278]
I didn't find a CONTRIBUTING.md file or any other contributing guide on how to send merge requests. I was wondering if this repo takes code contributions at all and if it does, what is the process?

**Comment by Ajaxy** [comment]
Hey! What exactly did you want to add a pull request about?

**Comment by mohammadamin16** [comment]
IDK. bug fixes, new features. I just want to be a part of this :)

**Comment by Ajaxy** [comment]
We don't have a specific contribution guide and it's quite rare when outsource PRs can be merged as it, but feel free to create start with some small improvement, we will definitely check your PR out.

**Comment by mohammadamin16** [comment]
That's great.
I'll send you some soon.
