### ISSUE TITLE
Nginx reverse proxy API error: WebSocket connection to'wss://...' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by forodo** [Ajaxy/telegram-tt#28]
When I want to reverse proxy the website, I cannot reverse proxy the WSS:// link, and the browser prompts the following error:
```
WebSocket connection to'wss://pluto.web.telegram.org/apiws' failed: Error during WebSocket handshake: Unexpected response code: 404
```

![02](https://user-images.githubusercontent.com/54703881/120894290-34c2e700-c64a-11eb-9a75-66ed409b8e07.png)

Nginx has added the following:
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
```

Hope you can help me!

**Comment by Ajaxy** [comment]
Please feel free to reopen providing more details if the issue is still relevant.
