### ISSUE TITLE
Exclude `dist` from the repo

### ISSUE THREAD

**Issue by alex-kinokon** [Ajaxy/telegram-tt#284]
Would you consider removing the `dist` folder from the repo? It’s easy to generate a lot of git conflicts with the folder checked in.

**Comment by Ajaxy** [comment]
Unfortunately, we can not, as it is used as a part of our deployment process.

**Comment by Haarolean** [comment]
@Ajaxy have you considered using git LFS or github pages for this? Currently cloning a repo takes about one gigabyte bandwidth and disk usage. Even if the dist directory is 300mb, every change is reflected in git and we get the sizes as we have now.
