### ISSUE TITLE
Images From Clipboard Get Sent As Files

### ISSUE THREAD

**Issue by fweth** [Ajaxy/telegram-tt#288]
When I paste an image in Chrome, it gets sent as file instead of an image. This is different in `web.telegram.org/k` and it was also different in `web.telegram.org/a` since recently, not sure if the client changed or Chrome changed the image pasting behaviour.

This is my Chrome version: 118.0.5993.10 (Official Build) dev (64-bit)

**Comment by korenskoy** [comment]
Try changing the sending method?

![image](https://github.com/Ajaxy/telegram-tt/assets/285244/721d1c43-eb65-4415-b891-04ce8b3e1297)

**Comment by fweth** [comment]
Thank you so much, that was it. The setting is also persistent, as it seems :)
