### ISSUE TITLE
The damn file ordering while upload

### ISSUE THREAD

**Issue by Porkechebure** [Ajaxy/telegram-tt#300]
If you upload a bunch of video file telegram just orders them the way he likes, they should be ordered in the file name order (or let us choose or reorder them) instead of needing to put them 1 by 1.

Fix this,

For example if I have video_01.mp4, then 02, 03, 04 etc. Once dragged it orders them like
Video 03
Video 04
Video 01
Video 02

And so on, and the thing changes randomly from time to time
Example
![image](https://github.com/Ajaxy/telegram-tt/assets/3466040/8d4d84bb-bc83-4e80-9208-c0f015797569)

They're not ordered by name...
They're not ordered by size...
They're not ordered by date...

WTF??? How you order them? By a random algorithm to purposefully shuffle them?

They're just taken 2 by 2 and ordered like this LOL

Do I have to write a bot to upload files or what?
We can't reorder them, we can't touch them. We just have to upload them 1 by 1. Very approriate and comfortable design

**Comment by Ajaxy** [comment]
You seem to be using the outdated web version. Please, consider moving to web.telegram.org/a.
