### ISSUE TITLE
Left Search: Not working for newly created channels

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#304]
Steps to reproduce:
- Create a new channel.
- Copy channel name.
- Paste the channel name to the Left Search input.
- Search result is empty.

**Comment by monster898** [comment]
Looks like this has been fixed already.

**Comment by Ajaxy** [comment]
Yep, thanks for the heads-up. 1ca211978c7b1eae668626c832f3851b7b88e975, 82af54555ce24e084b3db7f7834b2366fe258933.
