### ISSUE TITLE
New Group: Allow to manually send invites to users restricted to be added automatically 

### ISSUE THREAD

**Issue by Ajaxy** [Ajaxy/telegram-tt#306]
Some users restrict adding them to new groups automatically. Telegram clients need to suggest sending them invite links in direct messages instead.

Leverage https://core.telegram.org/constructor/updateGroupInvitePrivacyForbidden.

Designs are missing but can be implemented in a modal window above the newly created chat, similar to iOS.

Examples from other clients:

<img src="https://github.com/Ajaxy/telegram-tt/assets/357153/f3f91872-fcd6-44ac-be44-fba83c353c21" width="300" /> <img src="https://github.com/Ajaxy/telegram-tt/assets/357153/1030514b-f019-4579-9671-c16976a7cdbf" width="300" />

**Comment by rohit-4321** [comment]
Hey, @Ajaxy could you please give a little more info about this issue. What i can see, is while adding new user to the group in group setting, there is a modal for sending invitation. I believe thats what this is issue about or something else???

![image](https://github.com/Ajaxy/telegram-tt/assets/68504107/548404fe-13de-4060-b290-b6fa1e82be75)
![image](https://github.com/Ajaxy/telegram-tt/assets/68504107/40efd5c6-9cf0-4bb5-916a-90bb76ca7194)

**Comment by Ajaxy** [comment]
Yep, that is already implemented in 4d70ae306d33842122f4917ab119225b6c747f48. Thanks for an update, closing this one.
