### ISSUE TITLE
Writing a colon ":" followed by "D" results in an unexpected behaviour

### ISSUE THREAD

**Issue by astaruch** [Ajaxy/telegram-tt#31]
Hello,

Nice project!

When I am writing a message, which starts with a colon ":", I got a pop-up with emojis:
![Screenshot from 2021-06-16 14-07-09](https://user-images.githubusercontent.com/13131548/122216649-e9f86900-ceac-11eb-8501-6c8c4685304b.png)
This would be probably OK for a colon, but when I am writing ":D" smiley, it offers as a first emoji the :100: (100) or a :dress: (dress):
![Screenshot from 2021-06-16 14-05-32](https://user-images.githubusercontent.com/13131548/122216819-14e2bd00-cead-11eb-8f93-31c65d03f584.png)

This results into situation, when I can either press ESC and close the pop-up, or I will mistakenly send the :100: / :dress: emoji:, while I wanted to send classical ":D" or :smiley: : 
![Screenshot from 2021-06-16 14-14-34](https://user-images.githubusercontent.com/13131548/122217058-56736800-cead-11eb-9a9b-9812799599cb.png)

Is there a way how to disable this functionality?

EDIT: Just found that Telegram has own bug site, and found a user with similar question resolved to fixed: https://bugs.telegram.org/c/5838

**Comment by astaruch** [comment]
Hello, why have you closed this? The problem is still there

**Comment by Ajaxy** [comment]
We have disabled single-letter hints, so typing `:D + <Enter>` does not select an emoji now.
