### ISSUE TITLE
bug(ui): white stripe under the message

### ISSUE THREAD

**Issue by nikpivkin** [Ajaxy/telegram-tt#335]
The white stripe appears if I scroll through the post a bit.
<img width="814" alt="Screenshot 2023-12-25 at 12 29 14" src="https://github.com/Ajaxy/telegram-tt/assets/100182843/0129e018-76f1-4090-96e1-2f1e69c55bab">

Without scrolling:
<img width="727" alt="image" src="https://github.com/Ajaxy/telegram-tt/assets/100182843/7f50e204-f98d-4aed-a0d8-13160dc9bb3b">

**Comment by ulugmer** [comment]
That's not a bug. That line shows where the scroll is beginning.
