### ISSUE TITLE
Please share codeStyleSettings.xml 

### ISSUE THREAD

**Issue by fadakar** [Ajaxy/telegram-tt#339]
Please share codeStyleSettings.xml ( Jetbrains ) for better pull requests

**Comment by Ajaxy** [comment]
Just follow the [ESLint rules](https://github.com/Ajaxy/telegram-tt/blob/master/.eslintrc) for the project and make sure to not ignore pre-commit hooks.

**Comment by fadakar** [comment]
thanks
