### ISSUE TITLE
Animation and theme toggle does not saves after app reload

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Ajaxy/telegram-tt#36]
Disable animation, enable dark mode, reload - and you will see again animations and white theme.

**Comment by Ajaxy** [comment]
Hey @vitaly-zdanevich, what are your browser and OS versions?

**Comment by vitaly-zdanevich** [comment]
Firefox, Gentoo.

**Comment by Ajaxy** [comment]
Can you try now with 1.1.16?

**Comment by vitaly-zdanevich** [comment]
Opened it now, I see the version is `1.2.1`, and for the first time I see dark version here, and no animations (as I want).
