### ISSUE TITLE
.JPEG has no "send in a quick way" option but .JPG has

### ISSUE THREAD

**Issue by lycantropos** [Ajaxy/telegram-tt#49]
When I'm trying to attach picture with .JPG suffix I see these 2 options (and most of the time choose the last one)
<img width="721" alt="Screen Shot 2021-07-14 at 00 11 23" src="https://user-images.githubusercontent.com/15193952/125525648-51e51f81-0bd5-4ddb-a5e6-78f0390ec9fb.png">
but Firefox 89.0.2 (64-bit) on macOS saves images as .JPEG and I don't have the second option while trying to attach them and that's odd.

**Comment by Ajaxy** [comment]
Hey, can you upload the original file somewhere so I can test with it?

**Comment by lycantropos** [comment]
the only way I can reproduce is by moving downloaded image from "Downloads" in Firefox
<img width="468" alt="image" src="https://user-images.githubusercontent.com/15193952/125615635-81a75c8c-73e1-48d6-ba0e-03e16f120f21.png">
If I do so from "Finder" it works.

**Comment by Ajaxy** [comment]
@lycantropos Please confirm this is fixed for you in v1.15.19.

**Comment by lycantropos** [comment]
It works, indeed, thanks!
