### ISSUE TITLE
React devtools not working

### ISSUE THREAD

**Issue by maxjayne98** [Ajaxy/telegram-tt#56]
Hi
I have a problem with devtools.
React extension can't dedicate I'm running a react project therefore react devtools is not working.
How should I enable devtools ?

**Comment by fedyk** [comment]
The project is based on a custom implementation of reactive UI library: [teact](https://github.com/Ajaxy/telegram-tt/tree/master/src/lib/teact). It relies on `jsx` as React (and a bit similar API), but it does support React Dev Tools.

**Comment by Ajaxy** [comment]
@fedyk I assume you wanted to say

> but it does **not** support React Dev Tools

That would be correct.

**Comment by hanayashiki** [comment]
replace teact with react

**Comment by Ajaxy** [comment]
No way.

**Comment by dovranJorayev** [comment]
@Ajaxy is behavior of code written in  teact will broke if i will switch to react/preact. I assume public API of it bit close to react. Am i right?

**Comment by Ajaxy** [comment]
In most cases it should be fine, but that was never tested.
