### ISSUE TITLE
Parameters for bot commands (e.g. /alert 30min Check groceries list) are not passed when pressing ENTER key

### ISSUE THREAD

**Issue by reinhart1010** [Ajaxy/telegram-tt#57]
As in https://github.com/Ajaxy/telegram-tt/commit/a185fd940776ee3e5cd361521ecd153d297d1819 there's a new tooltip for bot commands. However, if I type the message box like this (e.g. in a group chat) and press the ENTER key:

```
/command@bot parameters
```

The app will only send the

```
/command@bot
```

message instead.

Some bots such as [@AlertBot](https://t.me/alertbot) require parameters to be passed along the command, such as `/alert 30min Check groceries list`, so this could distract the workflow for some Telegram users.

This issue does not occur on WebK and mobile apps as well.

**Comment by Ajaxy** [comment]
Thanks for the report. Fixed in d2b2ee69031c5f60cec19c8fc5a37ca93dc30010.
