### ISSUE TITLE
Error: Could not find a matching Constructor ID

### ISSUE THREAD

**Issue by ingria** [Ajaxy/telegram-tt#58]
```
[ERROR] - [Unhandled error while receiving data]
[ERROR] - [Error: Could not find a matching Constructor ID for the TLObject that was supposed to be
        read with ID 253890367. Most likely, a TLObject was trying to be read when
         it should not be read. Remaining bytes: 480]
```

This error needs to be handled, because it can cause very serious problems in some places (e.g. chat list or message history not being loaded).

Fun fact: this error also often [happens](https://github.com/LonamiWebs/Telethon/issues/1429) in Telethon, which GramJS is based on.

**Comment by Ajaxy** [comment]
Fixed in cf2db92c6155ac37cfa19797a4b4892a1745b771.
