### ISSUE TITLE
Wrong colors in dark theme

### ISSUE THREAD

**Issue by ingria** [Ajaxy/telegram-tt#59]
Some colors are taken from the hardcoded `-rgb` variables in `_variables.scss`. For example, button hover color:

<img  src="https://user-images.githubusercontent.com/2178368/131198860-8d6b2405-ea06-4a7b-9897-51ad26aa240b.png">

Also some elements in Composer, Audio, etc.

**Comment by Ajaxy** [comment]
Fixed in 1abb31e3ee4ce47d79f681f6c34f682087384f74.
