### ISSUE TITLE
Bugs in emoji input

### ISSUE THREAD

**Issue by ingria** [Ajaxy/telegram-tt#63]
1. After I paste or delete an emoji, the cursor position is resetted to the beginning:

https://user-images.githubusercontent.com/2178368/131233279-25334981-bbc2-49c4-a124-34d9c5b041a9.mp4

2. Emojis in the beginning of the message are not deleted on backspace key press and hold:

https://user-images.githubusercontent.com/2178368/131229171-632946f9-f68b-43e5-8cd5-40c11b52224a.mp4

3. Emojis selected from quick selection menu are not displayed correctly (default system font is used) and don't trigger sticker popover:

https://user-images.githubusercontent.com/2178368/131233191-6f8f917f-1f45-447f-ad7e-8e4e2ef8500b.mp4

**Comment by Ajaxy** [comment]
Fixed in 539e9885ed8b63cc8ec8ce244006351266ede872.

**Comment by ingria** [comment]
Problem 3 is still there

**Comment by Ajaxy** [comment]
What is your OS and browser?

**Comment by ingria** [comment]
Firefox 94, Ubuntu 20.04

**Comment by Ajaxy** [comment]
Can you still reproduce this?

**Comment by ingria** [comment]
Ok now, thanks
