### ISSUE TITLE
Feature request: ctrl+up keybind for "reply to previous message"

### ISSUE THREAD

**Issue by wojpawlik** [Ajaxy/telegram-tt#75]
Telegram Desktop:

https://user-images.githubusercontent.com/23058303/140512299-f94249d7-6335-4604-a007-89e2208086d4.mp4

![Zrzut ekranu z 2021-11-05 12-23-41](https://user-images.githubusercontent.com/23058303/140512751-88c87f07-0100-4620-8c0c-c9d4fcb7df89.png)

**Comment by Ajaxy** [comment]
Added in 1f02f2b7150824214b3f8432d5c0525f2e6dcdb3.

**Comment by wojpawlik** [comment]
![image](https://user-images.githubusercontent.com/23058303/149423210-8579842c-be7d-4542-97fa-8a0e6fa0cdca.png)

**Comment by Ajaxy** [comment]
What do these screenshots represent?
