### ISSUE TITLE
When I add Telegram web Z to the home screen, I get no connection

### ISSUE THREAD

**Issue by Suburbanno** [Ajaxy/telegram-tt#76]
here the option to add the home screen
![Screenshot_20211113-124426_Bromite.png](https://user-images.githubusercontent.com/13632826/141650129-73947be6-93cb-4bdb-a73a-814e675ec39a.png)
Once added, when I enter I already receive the message of no connection
![Screenshot_20211113-124334_Bromite.png](https://user-images.githubusercontent.com/13632826/141650164-50b01c68-7d3e-43d0-bb6f-803505b3b786.png)
even after deleting PWA, I go back to the normal browser and still have no connection
![Screenshot_20211113-124447_Bromite.png](https://user-images.githubusercontent.com/13632826/141650179-974ac1c2-788a-40f1-88cc-2c9889ed92ab.png)

**Comment by Suburbanno** [comment]
@Ajaxy hey, can you help me with this? Any solution?

**Comment by Ajaxy** [comment]
Can you provide more information? Is it related to installed app or not anymore?

**Comment by Suburbanno** [comment]
It is related to Telegram Web Z, it works normally in the Android Browser, but when I use the option "Add the app to the home screen" the WebZ is waiting for connection, both in PWA and when I open it in the Browser again, this is fixed when clear your browser data and log in again.

**Comment by Ajaxy** [comment]
Can you please provide console logs/output?

**Comment by Suburbanno** [comment]
how get logs?

**Comment by Ajaxy** [comment]
Was the issue resolved for you?

**Comment by Suburbanno** [comment]
Yes, my browser was blocking connection of PWA apps
