### ISSUE TITLE
Favicon in tab red dot for unread>0

### ISSUE THREAD

**Issue by nyir** [Ajaxy/telegram-tt#79]
Hey there!  I swear that at some point when I had unread messages there was a red dot in the favicon so I could easily know to go check for those messages, but I have not seen it for a couple months now.  Is this something that broke, something with my side (cache, cookies, &c), or was it never there and my brain is making this up?

Chromebook: 94.0.4606.124 (Official Build) (32-bit)

**Comment by Ajaxy** [comment]
Fixed in 5f988d47.
