### ISSUE TITLE
Emoji menu bug

### ISSUE THREAD

**Issue by eugenekv** [Ajaxy/telegram-tt#80]
Some Emoji merged in one placeholder and the word "Objects" is visible
![pic](https://user-images.githubusercontent.com/15031311/144257892-02428c1c-f771-48c4-b16d-e20973c82c30.png)

**Comment by Ajaxy** [comment]
What's your OS and browser version?

**Comment by eugenekv** [comment]
macOS High Sierra, Firefox 94.0.2

**Comment by eugenekv** [comment]
![pic](https://user-images.githubusercontent.com/15031311/144596810-b8aea685-4921-47c5-8778-6e1ecb00bfbb.png)
All subcategory beginnings look like this
