### ISSUE TITLE
Notification settings change android app notification settings

### ISSUE THREAD

**Issue by danipoak** [Ajaxy/telegram-tt#82]
When changing the notification settings in the webz application it also changes the notification settings in the android app. For example, if I disable message preview on the web, message preview is subsequently disabled in android as well. This behavior is duplicated on Chrome, Firefox, and other Chromium based browsers.

**Comment by Ajaxy** [comment]
That is an expected behavior (this setting is shared among all native and web clients). Feel free to reopen if you are not agree.
