### ISSUE TITLE
The Telegram account that uses the virtual phone number to apply for is disabled when logging in in this version of the Telegram client.

### ISSUE THREAD

**Issue by StevenMichael3213** [Ajaxy/telegram-tt#86]
I am very glad that Telegarm web version supports voice call sharing screen and other functions.

But when I used this program to log in to Telegram that I applied for with my virtual phone number, I encountered a problem. Within a few minutes of my successful login, my mobile number was disabled. Then the other ports of this Telegram account are also logged out. When logging in again, it prompts 'This phone number is banned'. Do you know the reason for this? It's strange that it is normal when I log in on the android terminal.

Does this have anything to do with the gramjs library? Because I see that gramjs is based on Telethon, and Telethon is based on MTProto Mobile Protocol. But we are now using it on the web side. I don't know if this is one of the reasons?

**Comment by Ajaxy** [comment]
This can happen with any Telegram version when you use virtual phone number. You need to reach out to Telegram Support and ask them to unblock your account.
