### ISSUE TITLE
Accessibility, Attaching file is no screen reader friendly

### ISSUE THREAD

**Issue by DraganRatkovich** [Ajaxy/telegram-tt#89]
When I click the attach button in Telegram Web Z, nothing happens, but if I navigate through the screen reader object navigation and click the button, sometimes a window pops up where I need to press the Tab key to be able to find a word called: File , photo media, so pressing the above keys will open the corresponding window for file selection.
@Ajaxy Please make attaching a file screen reader friendly, as attaching a media file or any file from the web version of Telegram is difficult. p.s. this problem exists in previous versions as well.

**Comment by Ajaxy** [comment]
Can you elaborate, what would be the expected behavior here?

**Comment by DraganRatkovich** [comment]
@Ajaxy I already mentioned this in the issue comments section, although I will repeat it here: expected behavior - when the user using the screen reader clicks the attach button, a window should appear where the blind user has to select the appropriate option to attach an eyther file or photo ... Currently, when the user clicks the attach button, it is not shown when navigating with the Tab key. It takes some trickery to use the attaching option.

**Comment by Ajaxy** [comment]
Thank you, will take a look.

**Comment by MesterPerfect** [comment]
> Can you elaborate, what would be the expected behavior here?

Hi Ajaxy,
Let me answer expected behavior question 😊
When pressing Add an attachment button, 
The menu containing Photo or Video, File and Poll must be activated. 
current situation
The menu is activated only if the mouse pointer is hovered over it 
If you need a screenshot for clarification, I can help too

**Comment by DraganRatkovich** [comment]
@MesterPerfect I think the dev will be very helpful with the screenshot if you provide it. Thank you.

**Comment by MesterPerfect** [comment]
![MesterPerfect](https://user-images.githubusercontent.com/44323153/145958852-769c25b8-a94c-4005-af5b-0b0994e58b4f.gif)

**Comment by MesterPerfect** [comment]
> @MesterPerfect I think the dev will be very helpful with the screenshot if you provide it. Thank you.

Sure, no problem, I have attached screenshot.

**Comment by DraganRatkovich** [comment]
@Ajaxy Hi,
Is there any news regarding to this issue?

**Comment by DraganRatkovich** [comment]
> We are working on better accessibility support.

Happy to hear it.

**Comment by DraganRatkovich** [comment]
@Ajaxy I think this is a good place to ask rather than open a new issue on the repo. Is there any news made for accessibility or still in progress. I mean, Telegram web z has updated but not sure if there is anything new about accessibility. Maybe you can provide more details on exactly what part of the process is going on to improve accessibility?

**Comment by Ajaxy** [comment]
Hey! Still in progress.

**Comment by DraganRatkovich** [comment]
@Ajaxy Why are you closing the issue without any information about it? Have you fixed anything? If yes, please report and then close!

**Comment by DraganRatkovich** [comment]
@Ajaxy If you accidentally closed it, then it's okay, but if you thought I forgot about this issue, then think again. I've been waiting for this issue to be resolved since the day you said accessibility would be better.

**Comment by Ajaxy** [comment]
Added in bd507a328f57b1e234144970f02f3254d3e24700.

**Comment by korenskoy** [comment]
@DraganRatkovich @MesterPerfect

Hello.  Can you provide feedback on fixing this issue?  This would help us consider accessibility as one of the important factors in development in the future.
Thank you!

**Comment by DraganRatkovich** [comment]
Hello @korenskoy
The issue is fixed, the button works very well, just one improovement. If possible, add the ability to collapse the button for photos or videos and files, because when pressed once, the buttons are displayed there until the chat is closed. Pressing again does not help.

**Comment by korenskoy** [comment]
> Pressing again does not help.

@DraganRatkovich thank you for feedback! The issue with closing the attach menu when the button is clicked again will be fixed in an upcoming release
