### ISSUE TITLE
Why create treact instead of using react?

### ISSUE THREAD

**Issue by ahmedlhanafy** [Ajaxy/telegram-tt#9]
This is more of a discussion than a gh issue tbh, but I didn't know where to ask this and I'm very curious about this choice. Reading the codebase of treact I found that it only supports function components with hooks, but apart from that I didn't understand the choice; why go through the hassle of maintaining a UI library when React works perfectly fine. 

P.S: Web Z is frickin' awesome!

**Comment by Ajaxy** [comment]
Thank you for the feedback!

That was the original rule of the contest:

> The goal of the third round of the JavaScript contest was to continue working on a web version of Telegram without using third-party UI frameworks.

**Comment by zamarawka** [comment]
Hm, treact looks like copy-paste of preact with cutting out of some legacy api’s.
Feels like cheating… 🤷‍♂️
Anyway, legacy angular version was awful in 2020. Web Z is providing great ux.
