### ISSUE TITLE
Missing option to leave owned chats without deleting them for all members

### ISSUE THREAD

**Issue by StuckDuck7710** [Ajaxy/telegram-tt#97]
Currently, there is no way to delete a group chat or channel just for yourself if you're the owner. "**Delete and exit**" will permanently delete the chat for everyone:

![image](https://user-images.githubusercontent.com/71439748/147937217-06f9da13-c664-4b89-88aa-7fd1b87baf5e.png)
![image](https://user-images.githubusercontent.com/71439748/147937224-8a9de24f-8923-41fa-8e82-f253f1e7c0bc.png)

You can reproduce this by creating a channel or supergroup (doesn't matter if public or private), adding another account and attempt to leave the chat. You will see that the chat is gone for other members as well.

**Comment by Ajaxy** [comment]
Was your issue resolved?

**Comment by StuckDuck7710** [comment]
> Was your issue resolved?

I made a pull request, but it seems to be fixed now

**Comment by Ajaxy** [comment]
Ok, thank you.
