### ISSUE TITLE
Testing Teact components

### ISSUE THREAD

**Issue by mattborghi** [Ajaxy/telegram-tt#99]
Hi, I have been looking for a solution for testing components but I don't seem to find it.

For example, I created a simple `CustomButton` component as follows:

```jsx
import React from '../../../lib/teact/teact';

type OwnProps = {
  title: string;
};

const CustomButton = ({ title }: OwnProps) => {
  return (
    <button>{title}</button>
  );
};

export default CustomButton;
```

And the corresponding test:

```jsx
import renderer from 'react-test-renderer';
import React from '../../../lib/teact/teactn';
import CustomButton from './CustomButton';

describe('Custom Button', () => {
  const render = <CustomButton title="title" />;
  /* eslint-disable no-console */
  console.log(render);
  
 let component: renderer.ReactTestRenderer;
  beforeEach(() => {
    component = renderer.create(render);
  });

  test('renders snapshot', () => {
    const tree = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

Where the following error appears

> Objects are not valid as a React child (found: object with keys {componentInstance, type, props, children}). If you meant to render a collection of children, use an array instead.

That means that `renderer.create` expects a `ReactElement` but `Teact` creates a `VirtualElement`. Is there any way of bypassing this issue? 

Thanks in advance, 
Matias

**Comment by Ajaxy** [comment]
Hi, Matias. At the moment, Teact is not compatible with React plugins, including the testing library. Feel free to research if there are some possible ways to achieve that.
